const products = [
  // Necklaces
  {
    id: "bridal-multi-set",
    category: "necklaces",
    name: "Heritage Bridal Multi-Set",
    price: 2499,
    originalPrice: 4999,
    rating: 4.9,
    reviews: 128,
    image: "neckless/beidal,multi.set.webp",
    thumbnails: ["neckless/beidal,multi.set.webp", "neckless/bridal statement set.png", "neckless/bridal,gold set.png"],
    description: "A masterpiece of traditional craftsmanship, this multi-layered bridal set captures the essence of royal Indian heritage. Each layer is meticulously designed with intricate patterns and gold-polish finish, making it the perfect centerpiece for your wedding day.",
    features: ["316L Stainless Steel Base", "24K Gold Vacuum Plating", "Hypoallergenic & Skin-Safe", "Adjustable Length with Dori"],
    material: "Surgical Grade Stainless Steel, Synthetic Rubies, Kundan Work",
    weight: "250g",
    trust: ["100% Authentic", "Easy 30-Day Returns", "Secure Payment"]
  },
  {
    id: "bridal-statement-set",
    category: "necklaces",
    name: "Royal Bridal Statement Set",
    price: 1899,
    originalPrice: 3499,
    rating: 4.8,
    reviews: 95,
    image: "neckless/bridal statement set.png",
    thumbnails: ["neckless/bridal statement set.png", "neckless/bridal,gold set.png", "neckless/beidal,multi.set.webp"],
    description: "Make a bold entrance with our Royal Bridal Statement Set. Designed for the modern bride who appreciates classic aesthetics, this set offers a stunning balance of weight and elegance.",
    features: ["Tarnish-Resistant Coating", "Premium Hand-Set Stones", "Includes Matching Earrings", "Lightweight for Long Wear"],
    material: "High-Polished Steel, AAA Grade Cubic Zirconia",
    weight: "180g",
    trust: ["Handcrafted Quality", "Express Shipping", "Premium Packaging"]
  },
  {
    id: "bridal-gold-set",
    category: "necklaces",
    name: "Maharani Gold Choker Set",
    price: 1599,
    originalPrice: 2999,
    rating: 5.0,
    reviews: 64,
    image: "neckless/bridal,gold set.png",
    thumbnails: ["neckless/bridal,gold set.png", "neckless/celestial choker.jpg", "neckless/beidal,multi.set.webp"],
    description: "The Maharani Choker is a celebration of opulence. Its wide profile sits perfectly on the neckline, adorned with traditional motifs that reflect the light beautifully.",
    features: ["Intricate Filigree Work", "Deep Gold Finish", "Comes with Maang Tikka", "Anti-Allergy Material"],
    material: "Stainless Steel, Gold Foil Accents",
    weight: "120g",
    trust: ["Authentic Design", "Gift Box Included", "Secure Checkout"]
  },
  {
    id: "celestial-choker",
    category: "necklaces",
    name: "Celestial Starry Choker",
    price: 899,
    originalPrice: 1599,
    rating: 4.7,
    reviews: 42,
    image: "neckless/celestial choker.jpg",
    thumbnails: ["neckless/celestial choker.jpg", "neckless/dimond,set.png", "neckless/rose,gold,set.jpg"],
    description: "Inspired by the night sky, the Celestial Choker features delicate starry pendants that shimmer with every movement. A versatile piece for both festive and evening wear.",
    features: ["Minimalist Design", "Dainty Chain Link", "Perfect for Layering", "Sweat-Proof Plating"],
    material: "Rose Gold Plated Steel, Micro-Pavé Zirconia",
    weight: "45g",
    trust: ["Modern Style", "Fast Delivery", "Quality Guaranteed"]
  },
  {
    id: "collection-jewellery",
    category: "necklaces",
    name: "Aura Signature Collection Set",
    price: 1299,
    originalPrice: 2299,
    rating: 4.9,
    reviews: 87,
    image: "neckless/collection_jwellery.png",
    thumbnails: ["neckless/collection_jwellery.png", "neckless/multicolor_set.png", "neckless/ethnic,set.png"],
    description: "A versatile addition to any jewellery box, our Signature Collection Set features a timeless necklace design that complements both ethnic and western attire.",
    features: ["Signature Aura Polish", "Durable Lobster Clasp", "Scratch-Resistant Surface", "Elegant Gift Box"],
    material: "Silver-Finished Stainless Steel",
    weight: "95g",
    trust: ["Exclusive Design", "3-Year Warranty on Polish", "Skin Friendly"]
  },
  {
    id: "diamond-set-necklace",
    category: "necklaces",
    name: "Eternal Diamond Illusion Set",
    price: 2199,
    originalPrice: 3999,
    rating: 4.9,
    reviews: 56,
    image: "neckless/dimond,set.png",
    thumbnails: ["neckless/dimond,set.png", "neckless/celestial choker.jpg", "neckless/rose,gold,set.jpg"],
    description: "Experience the brilliance of diamonds without the price tag. Our Illusion Set uses precision-cut stones and a unique setting to maximize shimmer and fire.",
    features: ["High-Dispersion Stones", "Rhodium Plated Steel", "Security Chain Included", "Brilliant Cut Quality"],
    material: "Rhodium Over Steel, Premium CZ Stones",
    weight: "110g",
    trust: ["Luxury Look", "Conflict-Free Stones", "Premium Storage Box"]
  },
  {
    id: "ethnic-set",
    category: "necklaces",
    name: "Temple Heritage Ethnic Set",
    price: 1399,
    originalPrice: 2599,
    rating: 4.8,
    reviews: 73,
    image: "neckless/ethnic,set.png",
    thumbnails: ["neckless/ethnic,set.png", "neckless/festivl,necklac.jpg", "neckless/beidal,multi.set.webp"],
    description: "Our Temple Heritage set features traditional Indian motifs inspired by ancient architecture. A soulful piece that brings a touch of history to your ensemble.",
    features: ["Antique Gold Finish", "Hand-Embossed Details", "Traditional Jhumka Earrings", "Lightweight Comfort"],
    material: "Matte Gold Plated Steel, Synthetic Pearls",
    weight: "140g",
    trust: ["Artisanal Craft", "Secure Shipping", "Best Price Guarantee"]
  },
  {
    id: "festive-necklace",
    category: "necklaces",
    name: "Diwali Sparkle Festive Necklace",
    price: 749,
    originalPrice: 1299,
    rating: 4.6,
    reviews: 112,
    image: "neckless/festivl,necklac.jpg",
    thumbnails: ["neckless/festivl,necklac.jpg", "neckless/celestial choker.jpg", "neckless/multicolor_set.png"],
    description: "Add a pop of celebration to your festive outfit. Light, bright, and beautiful, this necklace is designed for non-stop comfort during festivals.",
    features: ["Vibrant Finish", "Adjustable Hook", "Tangle-Free Chain", "Ideal for Gifting"],
    material: "Gold Toned Alloy Steel",
    weight: "35g",
    trust: ["Festive Ready", "Eco-Friendly Packing", "Quick Returns"]
  },
  {
    id: "multicolor-set",
    category: "necklaces",
    name: "Navaratna Inspired Multicolor Set",
    price: 1699,
    originalPrice: 3199,
    rating: 4.7,
    reviews: 39,
    image: "neckless/multicolor_set.png",
    thumbnails: ["neckless/multicolor_set.png", "neckless/ethnic,set.png", "neckless/collection_jwellery.png"],
    description: "Bring the colors of the rainbow to your look. This multicolor set features stones in nine auspicious shades, perfect for adding variety to your jewellery collection.",
    features: ["Multi-Tone Stone Palette", "Gold Polish Accents", "Breathable Design", "Statement Piece"],
    material: "Stainless Steel, Multi-Colored Crystals",
    weight: "130g",
    trust: ["Vibrant Colors", "Handpicked Stones", "Trusted Quality"]
  },
  {
    id: "rose-gold-set",
    category: "necklaces",
    name: "Modern Rose Gold Minimalist Set",
    price: 999,
    originalPrice: 1799,
    rating: 4.8,
    reviews: 82,
    image: "neckless/rose,gold,set.jpg",
    thumbnails: ["neckless/rose,gold,set.jpg", "neckless/celestial choker.jpg", "neckless/dimond,set.png"],
    description: "The ultimate in modern chic. This rose gold set offers a subtle, sophisticated glow that works from morning meetings to candlelight dinners.",
    features: ["Premium Rose Gold Finish", "Sleek Contemporary Lines", "Hypoallergenic Comfort", "Includes Small Studs"],
    material: "Rose Gold PVD Plated Steel",
    weight: "55g",
    trust: ["Timeless Style", "Tarnish-Free", "Satisfied Customers"]
  },

  // Earrings
  {
    id: "diamond-earrings",
    category: "earrings",
    name: "Princess Cut Diamond Studs",
    price: 499,
    originalPrice: 999,
    rating: 4.9,
    reviews: 145,
    image: "earings/dimonds_earings.png",
    thumbnails: ["earings/dimonds_earings.png", "earings/miniround_earings.png", "earings/light,earing.png"],
    description: "Our Princess Cut Studs offer unparalleled brilliance. Simple yet striking, they are the essential 'diamond' earrings every woman needs.",
    features: ["Secure Butterfly Back", "High-Clarity Stones", "No-Green-Skin Guarantee", "Classic 4-Prong Setting"],
    material: "Surgical Steel, High-Grade CZ",
    weight: "5g",
    trust: ["Everyday Essential", "Secure Fit", "Premium Clarity"]
  },
  {
    id: "heavy-jhumka",
    category: "earrings",
    name: "Royal Heritage Heavy Jhumkas",
    price: 599,
    originalPrice: 1199,
    rating: 5.0,
    reviews: 92,
    image: "earings/heavi,jhumka.jpg",
    thumbnails: ["earings/heavi,jhumka.jpg", "earings/long_earings.jpg", "earings/sheaded_earings.png"],
    description: "These Heavy Jhumkas are a tribute to traditional Indian beauty. Adorned with delicate pearls and intricate gold work, they sway with grace.",
    features: ["Hand-Strung Pearls", "Antique Gold Texture", "Traditional Bell Shape", "Comfortable Weight Distribution"],
    material: "Temple Gold Finished Steel, Faux Pearls",
    weight: "35g",
    trust: ["Authentic Craft", "Traditional Look", "Best Seller"]
  },
  {
    id: "light-earrings",
    category: "earrings",
    name: "Daily Glow Lightweight Drops",
    price: 299,
    originalPrice: 599,
    rating: 4.7,
    reviews: 210,
    image: "earings/light,earing.png",
    thumbnails: ["earings/light,earing.png", "earings/mini aring.png", "earings/miniround_earings.png"],
    description: "Forget you're even wearing them. These lightweight drops provide just the right hint of shine for your everyday activities.",
    features: ["Feather-Light Construction", "Rose Gold Tones", "Flexible Hook", "Skin-Safe Metal"],
    material: "Polished Stainless Steel",
    weight: "3g",
    trust: ["All-Day Comfort", "Budget Friendly", "Quality Finish"]
  },
  {
    id: "long-earrings",
    category: "earrings",
    name: "Cascade Long Dangler Earrings",
    price: 549,
    originalPrice: 999,
    rating: 4.8,
    reviews: 67,
    image: "earings/long_earings.jpg",
    thumbnails: ["earings/long_earings.jpg", "earings/heavi,jhumka.jpg", "earings/sheaded_earings.png"],
    description: "Dramatic and elegant, our Cascade Danglers frame the face beautifully. Ideal for evening gowns and festive sarees alike.",
    features: ["Shoulder-Grazing Length", "Flexible Joint Design", "Micro-Stone Inlays", "Premium PVD Coating"],
    material: "Gold Plated Steel, Crystals",
    weight: "18g",
    trust: ["Sophisticated Look", "Durable Finish", "Verified Buyer Favorite"]
  },
  {
    id: "mini-aring",
    category: "earrings",
    name: "Classic Mini Hoop Arings",
    price: 199,
    originalPrice: 399,
    rating: 4.5,
    reviews: 320,
    image: "earings/mini aring.png",
    thumbnails: ["earings/mini aring.png", "earings/miniround_earings.png", "earings/light,earing.png"],
    description: "Our Mini Hoops are the ultimate versatile accessory. Small, sleek, and high-shine, they belong in every collection.",
    features: ["Easy Click Closure", "High-Mirror Polish", "Tarnish-Proof Steel", "Unisex Appeal"],
    material: "316L Stainless Steel",
    weight: "4g",
    trust: ["Timeless Basics", "Never Tarnishes", "Best Value"]
  },
  {
    id: "mini-round-earrings",
    category: "earrings",
    name: "Petite Round Crystal Studs",
    price: 249,
    originalPrice: 499,
    rating: 4.6,
    reviews: 188,
    image: "earings/miniround_earings.png",
    thumbnails: ["earings/miniround_earings.png", "earings/mini aring.png", "earings/dimonds_earings.png"],
    description: "Sophistication in a small package. These petite round studs feature a central crystal surrounded by a halo of gold-toned steel.",
    features: ["Understated Elegance", "Nickel-Free Posts", "Precise Crystal Setting", "Gift-Ready Box"],
    material: "Gold Finished Steel, Clear Crystal",
    weight: "6g",
    trust: ["Dainty Design", "Secure Backing", "Perfect Gift"]
  },
  {
    id: "shaded-earrings",
    category: "earrings",
    name: "Enchanted Ombre Shaded Jhumkas",
    price: 649,
    originalPrice: 1299,
    rating: 4.9,
    reviews: 43,
    image: "earings/sheaded_earings.png",
    thumbnails: ["earings/sheaded_earings.png", "earings/heavi,jhumka.jpg", "earings/long_earings.jpg"],
    description: "Featuring a unique color-gradient effect, these shaded jhumkas transition beautifully from deep pink to soft gold.",
    features: ["Unique Ombre Finish", "Traditional Bell Style", "Intricate Detailing", "Conversation Starter"],
    material: "Enamel Coated Steel, Gold Polish",
    weight: "22g",
    trust: ["Exclusive Tech", "Artistic Design", "30-Day Returns"]
  },

  // Bangles
  {
    id: "floral-bangle-set",
    category: "bangles",
    name: "Spring Bloom Floral Bangle Set",
    price: 899,
    originalPrice: 1599,
    rating: 4.8,
    reviews: 55,
    image: "bangals/floral,bangl,set.webp",
    thumbnails: ["bangals/floral,bangl,set.webp", "bangals/gold,bangals.png", "bangals/gold,bangals.png"],
    description: "Celebrate nature's beauty with our Floral Bangle Set. Etched with delicate flower motifs, these bangles add a feminine touch to any wrist.",
    features: ["Precision Laser Etching", "Openable Clasp for Comfort", "Stacked Look", "Premium Shine"],
    material: "316L Stainless Steel",
    weight: "65g",
    trust: ["Durable Shine", "Comfort Fit", "Elegant Packaging"]
  },
  {
    id: "gold-bangles",
    category: "bangles",
    name: "Royal 24K Gold Bangle Set",
    price: 699,
    originalPrice: 1299,
    rating: 4.9,
    reviews: 120,
    image: "bangals/gold,bangals.png",
    thumbnails: ["bangals/gold,bangals.png", "bangals/floral,bangl,set.webp", "bangals/floral,bangl,set.webp"],
    description: "Our signature gold-tone bangles provide the undeniable glow of real gold at an accessible price. Perfect for layering or wearing solo.",
    features: ["High-Mirror Gold Finish", "Tarnish-Resistant Surface", "Perfect Round Shape", "Standard Size 2.4/2.6/2.8"],
    material: "Gold Vacuum Plated Steel",
    weight: "45g",
    trust: ["Must Have Essential", "Traditional Glow", "Trusted Choice"]
  },

  // Rings
  {
    id: "diamond-ring",
    category: "rings",
    name: "Forever One Solitaire Ring",
    price: 399,
    originalPrice: 799,
    rating: 4.9,
    reviews: 280,
    image: "ring/dimond,ring.png",
    thumbnails: ["ring/dimond,ring.png", "ring/gold,nose,ring.webp", "ring/dimond,ring.png"],
    description: "The classic solitaire ring redesigned for durability. A stunning 1-carat equivalent stone sits atop a sleek, polished band.",
    features: ["Adjustable Size Band", "High-Set Crown", "Scintillating CZ Stone", "Wedding Ready"],
    material: "Rhodium Plated Steel, AAA CZ",
    weight: "4g",
    trust: ["Premium Look", "Universal Fit", "Elegant Presentation"]
  },
  {
    id: "gold-nose-ring",
    category: "rings",
    name: "Traditional Gold Nath / Nose Ring",
    price: 199,
    originalPrice: 399,
    rating: 4.4,
    reviews: 58,
    image: "ring/gold,nose,ring.webp",
    thumbnails: ["ring/gold,nose,ring.webp", "ring/dimond,ring.png", "ring/gold,nose,ring.webp"],
    description: "Complete your ethnic look with our delicate gold-toned nose ring. Designed for comfort and lasting shine.",
    features: ["Clip-On Design (No Piercing Needed)", "Skin-Safe Material", "Traditional Motifs", "Easy to Wear"],
    material: "Gold Plated Stainless Steel",
    weight: "2g",
    trust: ["Comfort First", "Quick Delivery", "Traditional Essential"]
  }
];

// For use in browser without modules
if (typeof window !== 'undefined') {
  window.productData = products;
}
